### PR TITLE
Map cycling of items to Q and E and directional buttons to NumPad

### PR DESCRIPTION
**Pull request by Fighter19**
Useful as a way to cycle between items.
For devices like the Steam Deck, all directional buttons have been mapped to the NumPad,
so that the menu can be navigated without the use of the touch screen.

### CODE REVIEW

**Comment by MotoLegacy** [comment]
Is there any reason you chose Q and E for item cycling over Mouse Wheel? MWheel would be more beneficial to everyone, unless there's something about Steam Deck/Steam Input I'm unaware of that makes this difficult.

**Comment by Fighter19** [comment]
Pressing left/right (on the numpad) will also cycle, so it's not required anyway.
I thought Q and E was a default binding for cycling through items in some games, so I included that as well.
(Someone else also mentioned Q and E before, so I assumed it was a default binding. Might not be a MC: Classic thing, however.)

I'm not sure if the directional keys should be bound to numpad or to the arrow keys (latter might be more common).

**Review by MotoLegacy — CHANGES_REQUESTED** [review]
Swap Q and E binds for Mouse Wheel and I'll be happy to approve. 

Not sure what you mean by directional keys.

**Comment by Fighter19** [comment]
Mouse Wheel needs a special callback to be installed (and is more likely to cause issues).

https://www.glfw.org/docs/latest/input_guide.html#scrolling

I will remove Q and E for now.

**Comment by Fighter19** [comment]
I pushed changes to the "mouse_wheel" branch of my fork to both CrossCraft and Stardust to allow cycling through items using the mouse wheel.

**Comment by IridescentRose** [comment]
Accepted onto SDC

**Comment by IridescentRose** [comment]
@Fighter19 Please bump the stardust version in the commit and use the feature you added to set up the mousewheel and we'll get this merged.

**Comment by Fighter19** [comment]
@IridescentRose I bumped the Stardust version and added the wheel binding.

**Review by IridescentRose — APPROVED** [review]

**Pull request merged**
